/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sprintjava;

/**
 *
 * @author Mhamdi Amar
 */
public class EvaluationChefParClient extends javax.swing.JFrame {

    /**
     * Creates new form PropositionRecetteClient
     */
    public EvaluationChefParClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jBT_supprimer5 = new javax.swing.JButton();
        jBT_supprimer2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Expérience");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 320, 171, 22);

        jLabel3.setFont(new java.awt.Font("DK Cool Crayon", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Chef Ali Ben Salah");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 60, 460, 30);

        jLabel4.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chef cuisinier et propriétaire de la brasserie \"NRJ Food\"");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 90, 580, 40);

        jLabel5.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Note Chef");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 160, 171, 22);

        jLabel6.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("09/11/1978");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 240, 200, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/star.png"))); // NOI18N
        jLabel7.setText("EvaluationRecette");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 160, 160, 30);

        jLabel8.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Né le");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 240, 171, 22);

        jLabel9.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Evaluation");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 450, 171, 22);

        jLabel10.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Commentaire");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 500, 171, 22);

        jLabel13.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("De");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 280, 171, 22);

        jLabel16.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tunisie");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 270, 200, 30);

        jLabel12.setFont(new java.awt.Font("DK Cool Crayon", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Ses recettes");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(190, 200, 171, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*", "**", "***", "****", "*****" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(390, 450, 60, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/chefaliBenSalah.jpg"))); // NOI18N
        jLabel15.setText("PhotoChef");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(590, 130, 180, 160);

        jTextField1.setFont(new java.awt.Font("DK Cool Crayon", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(430, 490, 220, 40);

        jComboBox1.setFont(new java.awt.Font("DK Cool Crayon", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gâteau rapide au chocolat", "Rainbow cake", "Galette bressane", "Coeurs sablés au chocolat blanc" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 200, 210, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("DK Cool Crayon", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Deux étoiles au Guide Michelin et élu chef de l’année en 2011 par ses pairs, Jean-François Piège a vu son amour des produits et du savoir-faire encouragé par l’exigence de grands chefs comme Bruno Cirino, Christian Constant ou Alain Ducasse.\n\nRéputé pour son perfectionnisme, il se définit comme un « révélateur d’ingrédients » et pratique son art en s’appuyant sur un élément essentiel : le produit. Connu du grand public après avoir fait partie du jury des éditions spéciales d’ « Un Dîner Presque Parfait », Jean-François Piège est depuis 2010 l’un des membres du jury de l’émission « Top Chef » diffusée sur M6. \n\nJean-François Piège a commencé avec Alain Ducasse au Plaza Athénée où il a obtenu trois étoiles au Guide Michelin puis, il est devenu chef des cuisines du Crillon à Paris (deux étoiles), avant de racheter en 2009 la brasserie parisienne Thoumieux avec Thierry Costes. En octobre 2010, il ouvre le restaurant gastronomique au 1er étage de la brasserie. En 2011, la maison s’enrichit de l’Hôtel Thoumieux composé de quinze chambres à l’âme d’une maison de campagne à la ville. En 2013, l’univers s’agrandit en accueillant la pâtisserie Gâteaux Thoumieux, toujours dans la rue Saint-Dominique à deux pas de l’hôtel et des restaurants.\n");
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(320, 320, 470, 120);

        jBT_supprimer5.setBackground(new java.awt.Color(51, 0, 0));
        jBT_supprimer5.setFont(new java.awt.Font("DK Cool Crayon", 1, 12)); // NOI18N
        jBT_supprimer5.setForeground(new java.awt.Color(255, 102, 0));
        jBT_supprimer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/deco.jpg"))); // NOI18N
        jBT_supprimer5.setText("Déconnexion");
        jBT_supprimer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_supprimer5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_supprimer5);
        jBT_supprimer5.setBounds(640, 20, 140, 30);

        jBT_supprimer2.setBackground(new java.awt.Color(51, 0, 0));
        jBT_supprimer2.setFont(new java.awt.Font("DK Cool Crayon", 1, 12)); // NOI18N
        jBT_supprimer2.setForeground(new java.awt.Color(255, 102, 0));
        jBT_supprimer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/ajoute.png"))); // NOI18N
        jBT_supprimer2.setText("Valider");
        jBT_supprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_supprimer2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBT_supprimer2);
        jBT_supprimer2.setBounds(460, 450, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/bg1.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 800, 600);

        jMenu4.setText("Accueil");
        jMenuBar1.add(jMenu4);

        jMenu1.setText("Chercher");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/rec.jpg"))); // NOI18N
        jMenuItem1.setText("Recettes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/chef.jpg"))); // NOI18N
        jMenuItem2.setText("Chefs");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Evaluation");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprintjava/img/rec.jpg"))); // NOI18N
        jMenuItem3.setText("Recettes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Proposer Recette");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new RechercheRecetteParClient().setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if (jComboBox1.getItemAt(0).equals("Gâteau rapide au chocolat")) {
            new EvaluationRecetteParClient().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new RechercheChefParClient().setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBT_supprimer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_supprimer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT_supprimer5ActionPerformed

    private void jBT_supprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_supprimer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT_supprimer2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new EvaluationRecetteParClient().setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluationChefParClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluationChefParClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluationChefParClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluationChefParClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvaluationChefParClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_supprimer2;
    private javax.swing.JButton jBT_supprimer5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
